### ISSUE TITLE
Commits appear to be erased

### ISSUE THREAD

**Issue by mlschechter** [sfeir-open-source/sonar-clover#37]
The changes I made to update this plugin to work with versions of SonarQube appear to have been erased from `master` in the merge process. Can you please let me know if there's anything that can be done to address this?

I really enjoyed helping out the project, and as such would have been proud to be listed among the project contributors.

Thanks!

**Comment by Tony-Proum** [comment]
Hello @mlschechter,

I'm sorry, it seems like when I squashed all commits in order to merge the request, my user have replace yours instead of create a co-authored commit. I really confuse about that, because I think that your work needs to be awarded.
In order to correct this mistake, I've rewrites the history to allows you to be part of the contributors of this project. 

I thought that it was important to get a clean history in order to be able to generate a release not automatically, but I'd not thought that this kind of intensive rewrites could mask the work of anybody.

I hope that this error will not bits our collaboration: I've to say that I really enjoyed to work on this subject together.

**Comment by Tony-Proum** [comment]
I think that it could be possible to re-push all commits independently in order to let you be "better ranked" in the contributor rank. I'll try to do it as soon as possible

**Comment by mlschechter** [comment]
Thanks - I appreciate it!

And thank you for getting a new version of the plugin released!
